version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm -i
      - save_cache:
          key:
            - "npm-packages"
          paths:
            - src/node_modules
      - run: npm run lint
      
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm -i
      - run:
          name: test
          command: npm run test
  
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key:
            - "npm-packages"
      - run: npm -i
      - run:
          name: analyze
          command: npm audit
          
workflows:
  workflow:
    jobs:
      - build
      - test:
          requires:
          - build
      - analyze:
          requires:
          - test
